In [6]:
from metric_learn import Covariance
from sklearn.datasets import load_iris
import pandas as pd

iris_data = load_iris()
# this is our data
X = iris_data['data']
# these are our constraints
Y = iris_data['target']


import numpy as np

In [2]:
Y = Y + np.random.random(len(Y))

In [3]:
from metric_learn import MLKR

In [4]:
c = MLKR().fit(X, Y)

X_new = c.transform()

In [7]:
pd.DataFrame(X_new)

             0          1          2         3
0    -7.921524   8.700649  -1.227309 -1.790341
1    -6.932043   7.962935  -1.562724 -1.700114
2    -7.200510   7.963335  -1.214035 -1.650270
3    -6.382315   7.427111  -1.901423 -1.785980
4    -7.921851   8.627341  -1.203413 -1.804295
5    -7.630310   8.828720  -2.322512 -2.061966
6    -6.836008   7.706501  -1.688309 -1.739901
7    -7.371142   8.311441  -1.613798 -1.848297
8    -6.084991   7.089740  -1.771709 -1.668629
9    -7.044141   8.021315  -1.556863 -1.813700
10   -8.359969   9.195771  -1.326174 -1.910613
11   -6.821087   7.848924  -1.976393 -1.920208
12   -7.029386   7.926137  -1.341557 -1.716147
13   -7.127221   7.578431  -0.593105 -1.468275
14  -10.152235  10.521147  -0.135857 -1.739667
15   -9.296538  10.018215  -1.354453 -1.999605
16   -8.701563   9.416781  -1.118921 -1.750949
17   -7.683060   8.579697  -1.479323 -1.771386
18   -8.150688   9.338482  -2.032696 -2.072809
19   -7.839590   8.686009  -1.615990 -1.899770
20   -7.399998   8.648412  -2.092201 -2.015492
21   -7.459678   8.480614  -1.922749 -1.863939
22   -8.428620   8.584401  -0.123215 -1.481591
23   -6.119796   7.727860  -2.995534 -1.932987
24   -6.017647   7.407878  -2.879086 -2.153471
25   -6.537537   7.826655  -2.133671 -1.858545
26   -6.626401   7.922520  -2.418726 -1.888142
27   -7.794831   8.711385  -1.497358 -1.871017
28   -7.921196   8.773957  -1.251204 -1.776386
29   -6.397070   7.522289  -2.116728 -1.883533
..         ...        ...        ...       ...
120   6.486356   2.425163 -19.067188 -4.737694
121   6.028820   1.575616 -16.523963 -4.067034
122   7.885921   2.242102 -21.292310 -5.527969
123   4.705495   2.837333 -15.858739 -4.108519
124   6.150222   2.436010 -18.570111 -4.786636
125   5.674113   3.062133 -18.617263 -5.074495
126   4.437354   2.911041 -15.533946 -4.044719
127   4.563393   2.775160 -15.756205 -4.153305
128   7.013010   1.687561 -18.635477 -4.615734
129   4.944455   3.429184 -17.620925 -4.923143
130   6.463940   2.771895 -19.327453 -5.071632
131   5.385761   3.843075 -19.780484 -5.469315
132   7.251474   1.566608 -18.887491 -4.596779
133   4.384281   2.990604 -15.649747 -4.337768
134   6.050021   1.892093 -17.073405 -4.705898
135   6.711538   2.930221 -20.133480 -5.038332
136   7.020836   1.673607 -19.093907 -4.657208
137   5.605462   2.450762 -17.414303 -4.645473
138   4.436700   2.764425 -15.486155 -4.072629
139   5.347436   3.023672 -17.715209 -4.525464
140   6.880696   2.051282 -19.134745 -4.618265
141   5.020925   3.222812 -17.316545 -4.254291
142   6.185189   1.633597 -16.866791 -4.230464
143   7.163103   1.973382 -19.699832 -4.890281
144   7.104077   1.952199 -19.578171 -4.710818
145   5.712427   2.675853 -17.733883 -4.309326
146   5.494668   2.400480 -16.521139 -4.133565
147   5.279277   2.723210 -17.039535 -4.360346
148   6.387866   1.930840 -18.270945 -4.517732
149   5.381261   2.165628 -16.419697 -4.302970

[150 rows x 4 columns]

In [8]:
import pandas as pd
pd.DataFrame(x).head()

NameError: name 'x' is not defined

In [9]:
pd.DataFrame(iris).head()

NameError: name 'iris' is not defined

In [10]:
import sys

In [11]:
sys.path.append("../code/")

In [12]:
from common_functions import *

In [13]:
df, dfc= create_region_df("Austin")

In [14]:
df = df.rename(columns={'house_num_rooms': 'num_rooms',
                                  'num_occupants': 'total_occupants',
                                  'difference_ratio_min_max': 'ratio_difference_min_max'})

#drop_rows_having_no_data
o = {}
for h in df.index:
    o[h]=len(df.ix[h][feature_map['Monthly+Static']].dropna())
num_features_ser = pd.Series(o)
drop_rows = num_features_ser[num_features_ser==0].index

df = df.drop(drop_rows)

In [15]:
df = df[(df.full_agg_available == 1)]

In [16]:
i = np.intersect1d(df.total_occupants.dropna().index, df.num_rooms.dropna().index)

In [17]:
df = df.ix[i]

In [18]:
def scale_0_1(ser, minimum=None, maximum=None):
    if minimum is not None:
        pass
    else:
        minimum = ser.min()
        maximum = ser.max()
    return (ser - minimum).div(maximum - minimum)

def normalise(df):
    new_df = df.copy()
    max_aggregate = df[["aggregate_%d" % i for i in range(1, 13)]].max().max()
    min_aggregate = df[["aggregate_%d" % i for i in range(1, 13)]].min().min()
    new_df[["aggregate_%d" % i for i in range(1, 13)]] = scale_0_1(df[["aggregate_%d" % i for i in range(1, 13)]],
                                                                   min_aggregate, max_aggregate)
    for col in ['area', 'total_occupants', 'num_rooms', 'ratio_min_max',
                'skew', 'kurtosis', 'variance', 'ratio_difference_min_max', 'p_25',
                'p_50', 'p_75']:
        new_df[col] = scale_0_1(df[col])
    return new_df

df = normalise(df)

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
clf = KNeighborsClassifier(n_neighbors=1)

In [21]:
features = flatten([['aggregate_%d' %i for i in range(1, 13)], ['area','num_rooms','total_occupants']])

In [102]:
appliance="fridge"
if appliance=="hvac":
    start, stop=5, 11
else:
    start, stop=1, 13
appliance_df = df.ix[df[['%s_%d' %(appliance,month) for month in range(start,stop)]].dropna().index]

In [114]:
k=5
out = {}
for home in appliance_df.index:
    distance = np.square(df[features]-appliance_df.ix[home][features]).sum(axis=1)
    distance.sort_values(inplace=True)
    distance = distance.drop([home])
    nghbrs = distance.head(k).index
    pred = appliance_df[['%s_%d' %(appliance,month) for month in range(start,stop)]].ix[nghbrs].mean()
    out[home] = pred

In [115]:
pred_df = pd.DataFrame(out).T

In [116]:
compute_rmse_fraction(appliance, pred_df,'Austin')

0.74272045535292686

In [117]:

from sklearn.datasets import load_iris

In [118]:
X_ml.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
count,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000
mean,-0.366935,0.048440,0.736116,0.200142,-0.258557,0.037397,-0.574550,0.060649,0.170200,-0.050086,0.123930,-0.259536,0.057587,-0.261346,-0.350501
std,0.210126,0.126923,0.291754,0.139328,0.179738,0.082074,0.328140,0.062127,0.118520,0.085260,0.166741,0.181537,0.061476,0.203486,0.232333
min,-1.085342,-0.146090,0.138410,-0.010534,-0.845068,-0.099929,-1.561849,-0.224631,0.014409,-0.333963,-0.234329,-0.777738,-0.123582,-1.058334,-1.265172
25%,-0.460134,-0.035447,0.553561,0.081033,-0.331567,-0.012060,-0.721752,0.037653,0.075618,-0.092335,0.026260,-0.358816,0.022395,-0.305607,-0.437625
50%,-0.323430,0.011700,0.715115,0.178526,-0.234538,0.027322,-0.525874,0.065943,0.166605,-0.048791,0.119653,-0.234811,0.059135,-0.193661,-0.287330
75%,-0.202806,0.113851,0.875251,0.280420,-0.129774,0.067867,-0.325580,0.105124,0.227036,0.007096,0.239366,-0.134844,0.089913,-0.132539,-0.183083
max,-0.066883,0.440178,1.465332,0.609046,-0.002834,0.427026,-0.145763,0.146215,0.505507,0.178940,0.548494,0.065822,0.197601,-0.067535,-0.098620

In [119]:
out_ml = {}
for month in range(start, stop):
    print month
    out_ml[month] = {}
    c = MLKR().fit(df.ix[appliance_df.index][features].values, appliance_df['%s_%d' %(appliance, month)].reshape(-1,1))
    X_new = c.transform()
    X_ml = pd.DataFrame(X_new)
    X_ml.index = df.ix[appliance_df.index].index
    for home in appliance_df.index:
        distance = np.square(X_ml-X_ml.ix[home]).sum(axis=1)
        distance.sort_values(inplace=True)
        distance = distance.drop([home])
        nghbrs = distance.head(k).index
        pred =appliance_df['%s_%d' %(appliance, month)].ix[nghbrs].mean()
        out_ml[month][home] = pred

1
2
3
4
5
6
7
8
9
10
11
12

/Users/nipunbatra/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:5: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead

In [120]:
pred_df_ml = pd.DataFrame(out_ml)

In [121]:
pred_df_ml.columns = [['%s_%d' %(appliance, month) for month in range(start, stop)]]

In [122]:
pred_df_ml.head()

,fridge_1,fridge_2,fridge_3,fridge_4,fridge_5,fridge_6,fridge_7,fridge_8,fridge_9,fridge_10,fridge_11,fridge_12
26,50.697846,46.608086,52.363026,56.424841,62.488741,66.453043,81.447628,75.259913,73.917815,70.469724,60.682146,63.177921
59,31.273608,32.822973,40.395794,43.335540,66.089517,68.676951,53.626129,65.227222,55.375643,66.031770,55.603763,56.268450
94,41.163461,39.098297,45.345898,51.625264,49.385697,54.413420,62.449517,57.587403,53.905135,51.737373,40.954721,41.936932
135,21.318543,25.128103,29.407060,44.147050,48.829975,54.673427,39.991584,55.993813,53.450998,50.806487,39.275748,40.046715
222,64.632952,56.172557,64.177226,66.093009,76.288314,75.479321,76.520420,79.411981,76.012289,76.976624,68.048896,67.751685

In [123]:
compute_rmse_fraction(appliance, pred_df_ml,'Austin')

1.4134937846823088

In [ ]:
pred_df_ml.index